# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb98701c5c85903b1eaab03fd4db7cd870ed7edb498faf8382c9b9b7bfc7472e4f0d2b3b3868b54db2b588e339593bafc5238ffacdcbbeff88287c20ca3359f1

test:
  secret_key_base: 8fc2afa405cd52e4e2dde1d1a561afa41b4a4cf21739b0adb3e65495e5fb4325eded0a4b1f0d6121b073b0d041559ff4a8701a1b2d3a56ae997d38d7cccf955d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
